### ISSUE TITLE
Does node-impala work on Impala with Kerberos enabled

### ISSUE THREAD

**Issue by shuo-uber** [ufukomer/node-impala#10]
Hi, there, 

We have a cluster of Impala daemon nodes which requires Kerberos auth. I tried to use the lib to connect to those nodes and it was not successful. Here is the stack trace,

`{ Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`

The stack trace may not help much. I am not sure if it is something related to the Kerberos auth requirement. As least, I don't know how to configure this lib to use GSSAPI to authenticate against the cluster.

So my question is if this lib support GSSAPI or Kerberos for auth mech? If so, how to configure it.

Thanks,
Shuo

**Comment by ufukomer** [comment]
It does not support auth mechanisms.

**Comment by shuo-uber** [comment]
@ufukomer do you know some other lib that supports that or if you have a general idea on how to do it, I would like to take a shot and contribute back? Thanks a lot.

**Comment by ufukomer** [comment]
@shuo-uber did you read this? https://github.com/ufukomer/node-impala/issues/4#issuecomment-214581222 Maybe that gives you the basic idea. But I don't have any further information. If you do search, please share with me then we can improve this module.

**Comment by shuo-uber** [comment]
@ufukomer thanks. I will keep you posted.

**Comment by mingzhou** [comment]
Hi @ufukomer , is there any plan or schedule on kerberos support? Thanks.

**Comment by ufukomer** [comment]
@mingzhou nope. Do you have a plan?

**Comment by mingzhou** [comment]
@ufukomer no. I'm doing some survey. I might use impyla on Python, instead of nodejs because it's fill-feature support. Thanks.
