### ISSUE TITLE
query 1024 row limit

### ISSUE THREAD

**Issue by FloPersus** [ufukomer/node-impala#11]
Hi,

When I want to paging a query with LIMIT and OFFSET clauses, 
I only have 24 rows when LIMIT = 1000 and OFFSET = 1000 

the result of request count is 2152.

I think this is an issue.

**Comment by ufukomer** [comment]
Beeswax limits the query result. It is not possible to increase the size by setting _fetch_size_ [here](https://github.com/ufukomer/node-impala/blob/master/src/thrift/beeswax.thrift#L129). Let's use the **HiveServer2** #4. 🙈
