### ISSUE TITLE
All my queries return only 1024 lines and then stops?

### ISSUE THREAD

**Issue by janhoon** [ufukomer/node-impala#15]
I am connecting to an impala db via node-impala from my node server, but every time I do a query (unless the limit is less than) the result return 1024 line from the db. Even if I SELECT * it returns 1024 lines form a db with over 6 million lines. I understand that beeswax reads 1024 lines at a time when querying, but why does it stop after the first run?

Please please help.
And thank you in advance to whomever gets back to me :)

**Comment by ufukomer** [comment]
https://github.com/ufukomer/node-impala/issues/11#issuecomment-274798646

**Comment by ufukomer** [comment]
9751a960edaf34f601b2cac65373b01686a52358
